default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: bart
  password: ''
test:
  <<: *default
  database: auth_kit_test
development:
  <<: *default
  database: auth_kit_development
production:
  <<: *default
  database: auth_kit_production
